### ISSUE TITLE
Please provide an AppImage for download

### ISSUE THREAD

**Issue by probonopd** [envsh/tox-homeserver#8]
https://github.com/envsh/tox-homeserver/blob/69e2ee1d863569238906e0df6db865c09939e4f4/tools/package.sh#L42

Please provide an AppImage for download on https://github.com/envsh/tox-homeserver/releases, thanks.

**Comment by envsh** [comment]
Just a new release with AppImage package.  https://github.com/envsh/tox-homeserver/releases

**Comment by probonopd** [comment]
Thank you.
